package bean;
// Generated 2017-12-12 10:39:43 by Hibernate Tools 3.5.0.Final

/**
 * TblBaozhang generated by hbm2java
 */
public class TblBaozhang implements java.io.Serializable {

	private TblBaozhangId id;

	public TblBaozhang() {
	}

	public TblBaozhang(TblBaozhangId id) {
		this.id = id;
	}

	public TblBaozhangId getId() {
		return this.id;
	}

	public void setId(TblBaozhangId id) {
		this.id = id;
	}

}
