package bean;
// Generated 2017-12-20 17:01:12 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * TblBaozhangId generated by hbm2java
 */
public class TblBaozhangId implements java.io.Serializable {

	private String status;
	private String branchCompany;
	private String districtCompany;
	private String costObjectId;
	private String costObjectName;
	private String entityId;
	private String entityName;
	private String costType;
	private String accountDate;
	private String accountPerson;
	private String startedDate;
	private String endedDate;
	private String accountType;
	private String businessType;
	private String accountMethod;
	private String electricType;
	private BigDecimal electricAmount;
	private BigDecimal electricPrice;
	private BigDecimal accountAmount;
	private BigDecimal tax;
	private String payMethod;
	private BigDecimal utilitiesFee;
	private BigDecimal sewageFee;
	private BigDecimal garbageFee;
	private String accountCenterName;
	private String accountCenterId;
	private String userId;
	private String advancePayment;
	private String settlementType;
	private String billType;
	private String is10kv;

	public TblBaozhangId() {
	}

	public TblBaozhangId(String status, String branchCompany, String districtCompany, String costObjectId,
			String costObjectName, String entityId, String entityName, String costType, String accountDate,
			String accountPerson, String startedDate) {
		this.status = status;
		this.branchCompany = branchCompany;
		this.districtCompany = districtCompany;
		this.costObjectId = costObjectId;
		this.costObjectName = costObjectName;
		this.entityId = entityId;
		this.entityName = entityName;
		this.costType = costType;
		this.accountDate = accountDate;
		this.accountPerson = accountPerson;
		this.startedDate = startedDate;
	}

	public TblBaozhangId(String status, String branchCompany, String districtCompany, String costObjectId,
			String costObjectName, String entityId, String entityName, String costType, String accountDate,
			String accountPerson, String startedDate, String endedDate, String accountType, String businessType,
			String accountMethod, String electricType, BigDecimal electricAmount, BigDecimal electricPrice,
			BigDecimal accountAmount, BigDecimal tax, String payMethod, BigDecimal utilitiesFee, BigDecimal sewageFee,
			BigDecimal garbageFee, String accountCenterName, String accountCenterId, String userId,
			String advancePayment, String settlementType, String billType, String is10kv) {
		this.status = status;
		this.branchCompany = branchCompany;
		this.districtCompany = districtCompany;
		this.costObjectId = costObjectId;
		this.costObjectName = costObjectName;
		this.entityId = entityId;
		this.entityName = entityName;
		this.costType = costType;
		this.accountDate = accountDate;
		this.accountPerson = accountPerson;
		this.startedDate = startedDate;
		this.endedDate = endedDate;
		this.accountType = accountType;
		this.businessType = businessType;
		this.accountMethod = accountMethod;
		this.electricType = electricType;
		this.electricAmount = electricAmount;
		this.electricPrice = electricPrice;
		this.accountAmount = accountAmount;
		this.tax = tax;
		this.payMethod = payMethod;
		this.utilitiesFee = utilitiesFee;
		this.sewageFee = sewageFee;
		this.garbageFee = garbageFee;
		this.accountCenterName = accountCenterName;
		this.accountCenterId = accountCenterId;
		this.userId = userId;
		this.advancePayment = advancePayment;
		this.settlementType = settlementType;
		this.billType = billType;
		this.is10kv = is10kv;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBranchCompany() {
		return this.branchCompany;
	}

	public void setBranchCompany(String branchCompany) {
		this.branchCompany = branchCompany;
	}

	public String getDistrictCompany() {
		return this.districtCompany;
	}

	public void setDistrictCompany(String districtCompany) {
		this.districtCompany = districtCompany;
	}

	public String getCostObjectId() {
		return this.costObjectId;
	}

	public void setCostObjectId(String costObjectId) {
		this.costObjectId = costObjectId;
	}

	public String getCostObjectName() {
		return this.costObjectName;
	}

	public void setCostObjectName(String costObjectName) {
		this.costObjectName = costObjectName;
	}

	public String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	public String getCostType() {
		return this.costType;
	}

	public void setCostType(String costType) {
		this.costType = costType;
	}

	public String getAccountDate() {
		return this.accountDate;
	}

	public void setAccountDate(String accountDate) {
		this.accountDate = accountDate;
	}

	public String getAccountPerson() {
		return this.accountPerson;
	}

	public void setAccountPerson(String accountPerson) {
		this.accountPerson = accountPerson;
	}

	public String getStartedDate() {
		return this.startedDate;
	}

	public void setStartedDate(String startedDate) {
		this.startedDate = startedDate;
	}

	public String getEndedDate() {
		return this.endedDate;
	}

	public void setEndedDate(String endedDate) {
		this.endedDate = endedDate;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public String getAccountMethod() {
		return this.accountMethod;
	}

	public void setAccountMethod(String accountMethod) {
		this.accountMethod = accountMethod;
	}

	public String getElectricType() {
		return this.electricType;
	}

	public void setElectricType(String electricType) {
		this.electricType = electricType;
	}

	public BigDecimal getElectricAmount() {
		return this.electricAmount;
	}

	public void setElectricAmount(BigDecimal electricAmount) {
		this.electricAmount = electricAmount;
	}

	public BigDecimal getElectricPrice() {
		return this.electricPrice;
	}

	public void setElectricPrice(BigDecimal electricPrice) {
		this.electricPrice = electricPrice;
	}

	public BigDecimal getAccountAmount() {
		return this.accountAmount;
	}

	public void setAccountAmount(BigDecimal accountAmount) {
		this.accountAmount = accountAmount;
	}

	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	public String getPayMethod() {
		return this.payMethod;
	}

	public void setPayMethod(String payMethod) {
		this.payMethod = payMethod;
	}

	public BigDecimal getUtilitiesFee() {
		return this.utilitiesFee;
	}

	public void setUtilitiesFee(BigDecimal utilitiesFee) {
		this.utilitiesFee = utilitiesFee;
	}

	public BigDecimal getSewageFee() {
		return this.sewageFee;
	}

	public void setSewageFee(BigDecimal sewageFee) {
		this.sewageFee = sewageFee;
	}

	public BigDecimal getGarbageFee() {
		return this.garbageFee;
	}

	public void setGarbageFee(BigDecimal garbageFee) {
		this.garbageFee = garbageFee;
	}

	public String getAccountCenterName() {
		return this.accountCenterName;
	}

	public void setAccountCenterName(String accountCenterName) {
		this.accountCenterName = accountCenterName;
	}

	public String getAccountCenterId() {
		return this.accountCenterId;
	}

	public void setAccountCenterId(String accountCenterId) {
		this.accountCenterId = accountCenterId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getAdvancePayment() {
		return this.advancePayment;
	}

	public void setAdvancePayment(String advancePayment) {
		this.advancePayment = advancePayment;
	}

	public String getSettlementType() {
		return this.settlementType;
	}

	public void setSettlementType(String settlementType) {
		this.settlementType = settlementType;
	}

	public String getBillType() {
		return this.billType;
	}

	public void setBillType(String billType) {
		this.billType = billType;
	}

	public String getIs10kv() {
		return this.is10kv;
	}

	public void setIs10kv(String is10kv) {
		this.is10kv = is10kv;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblBaozhangId))
			return false;
		TblBaozhangId castOther = (TblBaozhangId) other;

		return ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
				&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getBranchCompany() == castOther.getBranchCompany())
						|| (this.getBranchCompany() != null && castOther.getBranchCompany() != null
								&& this.getBranchCompany().equals(castOther.getBranchCompany())))
				&& ((this.getDistrictCompany() == castOther.getDistrictCompany())
						|| (this.getDistrictCompany() != null && castOther.getDistrictCompany() != null
								&& this.getDistrictCompany().equals(castOther.getDistrictCompany())))
				&& ((this.getCostObjectId() == castOther.getCostObjectId())
						|| (this.getCostObjectId() != null && castOther.getCostObjectId() != null
								&& this.getCostObjectId().equals(castOther.getCostObjectId())))
				&& ((this.getCostObjectName() == castOther.getCostObjectName())
						|| (this.getCostObjectName() != null && castOther.getCostObjectName() != null
								&& this.getCostObjectName().equals(castOther.getCostObjectName())))
				&& ((this.getEntityId() == castOther.getEntityId()) || (this.getEntityId() != null
						&& castOther.getEntityId() != null && this.getEntityId().equals(castOther.getEntityId())))
				&& ((this.getEntityName() == castOther.getEntityName()) || (this.getEntityName() != null
						&& castOther.getEntityName() != null && this.getEntityName().equals(castOther.getEntityName())))
				&& ((this.getCostType() == castOther.getCostType()) || (this.getCostType() != null
						&& castOther.getCostType() != null && this.getCostType().equals(castOther.getCostType())))
				&& ((this.getAccountDate() == castOther.getAccountDate())
						|| (this.getAccountDate() != null && castOther.getAccountDate() != null
								&& this.getAccountDate().equals(castOther.getAccountDate())))
				&& ((this.getAccountPerson() == castOther.getAccountPerson())
						|| (this.getAccountPerson() != null && castOther.getAccountPerson() != null
								&& this.getAccountPerson().equals(castOther.getAccountPerson())))
				&& ((this.getStartedDate() == castOther.getStartedDate())
						|| (this.getStartedDate() != null && castOther.getStartedDate() != null
								&& this.getStartedDate().equals(castOther.getStartedDate())))
				&& ((this.getEndedDate() == castOther.getEndedDate()) || (this.getEndedDate() != null
						&& castOther.getEndedDate() != null && this.getEndedDate().equals(castOther.getEndedDate())))
				&& ((this.getAccountType() == castOther.getAccountType())
						|| (this.getAccountType() != null && castOther.getAccountType() != null
								&& this.getAccountType().equals(castOther.getAccountType())))
				&& ((this.getBusinessType() == castOther.getBusinessType())
						|| (this.getBusinessType() != null && castOther.getBusinessType() != null
								&& this.getBusinessType().equals(castOther.getBusinessType())))
				&& ((this.getAccountMethod() == castOther.getAccountMethod())
						|| (this.getAccountMethod() != null && castOther.getAccountMethod() != null
								&& this.getAccountMethod().equals(castOther.getAccountMethod())))
				&& ((this.getElectricType() == castOther.getElectricType())
						|| (this.getElectricType() != null && castOther.getElectricType() != null
								&& this.getElectricType().equals(castOther.getElectricType())))
				&& ((this.getElectricAmount() == castOther.getElectricAmount())
						|| (this.getElectricAmount() != null && castOther.getElectricAmount() != null
								&& this.getElectricAmount().equals(castOther.getElectricAmount())))
				&& ((this.getElectricPrice() == castOther.getElectricPrice())
						|| (this.getElectricPrice() != null && castOther.getElectricPrice() != null
								&& this.getElectricPrice().equals(castOther.getElectricPrice())))
				&& ((this.getAccountAmount() == castOther.getAccountAmount())
						|| (this.getAccountAmount() != null && castOther.getAccountAmount() != null
								&& this.getAccountAmount().equals(castOther.getAccountAmount())))
				&& ((this.getTax() == castOther.getTax()) || (this.getTax() != null && castOther.getTax() != null
						&& this.getTax().equals(castOther.getTax())))
				&& ((this.getPayMethod() == castOther.getPayMethod()) || (this.getPayMethod() != null
						&& castOther.getPayMethod() != null && this.getPayMethod().equals(castOther.getPayMethod())))
				&& ((this.getUtilitiesFee() == castOther.getUtilitiesFee())
						|| (this.getUtilitiesFee() != null && castOther.getUtilitiesFee() != null
								&& this.getUtilitiesFee().equals(castOther.getUtilitiesFee())))
				&& ((this.getSewageFee() == castOther.getSewageFee()) || (this.getSewageFee() != null
						&& castOther.getSewageFee() != null && this.getSewageFee().equals(castOther.getSewageFee())))
				&& ((this.getGarbageFee() == castOther.getGarbageFee()) || (this.getGarbageFee() != null
						&& castOther.getGarbageFee() != null && this.getGarbageFee().equals(castOther.getGarbageFee())))
				&& ((this.getAccountCenterName() == castOther.getAccountCenterName())
						|| (this.getAccountCenterName() != null && castOther.getAccountCenterName() != null
								&& this.getAccountCenterName().equals(castOther.getAccountCenterName())))
				&& ((this.getAccountCenterId() == castOther.getAccountCenterId())
						|| (this.getAccountCenterId() != null && castOther.getAccountCenterId() != null
								&& this.getAccountCenterId().equals(castOther.getAccountCenterId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getAdvancePayment() == castOther.getAdvancePayment())
						|| (this.getAdvancePayment() != null && castOther.getAdvancePayment() != null
								&& this.getAdvancePayment().equals(castOther.getAdvancePayment())))
				&& ((this.getSettlementType() == castOther.getSettlementType())
						|| (this.getSettlementType() != null && castOther.getSettlementType() != null
								&& this.getSettlementType().equals(castOther.getSettlementType())))
				&& ((this.getBillType() == castOther.getBillType()) || (this.getBillType() != null
						&& castOther.getBillType() != null && this.getBillType().equals(castOther.getBillType())))
				&& ((this.getIs10kv() == castOther.getIs10kv()) || (this.getIs10kv() != null
						&& castOther.getIs10kv() != null && this.getIs10kv().equals(castOther.getIs10kv())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getBranchCompany() == null ? 0 : this.getBranchCompany().hashCode());
		result = 37 * result + (getDistrictCompany() == null ? 0 : this.getDistrictCompany().hashCode());
		result = 37 * result + (getCostObjectId() == null ? 0 : this.getCostObjectId().hashCode());
		result = 37 * result + (getCostObjectName() == null ? 0 : this.getCostObjectName().hashCode());
		result = 37 * result + (getEntityId() == null ? 0 : this.getEntityId().hashCode());
		result = 37 * result + (getEntityName() == null ? 0 : this.getEntityName().hashCode());
		result = 37 * result + (getCostType() == null ? 0 : this.getCostType().hashCode());
		result = 37 * result + (getAccountDate() == null ? 0 : this.getAccountDate().hashCode());
		result = 37 * result + (getAccountPerson() == null ? 0 : this.getAccountPerson().hashCode());
		result = 37 * result + (getStartedDate() == null ? 0 : this.getStartedDate().hashCode());
		result = 37 * result + (getEndedDate() == null ? 0 : this.getEndedDate().hashCode());
		result = 37 * result + (getAccountType() == null ? 0 : this.getAccountType().hashCode());
		result = 37 * result + (getBusinessType() == null ? 0 : this.getBusinessType().hashCode());
		result = 37 * result + (getAccountMethod() == null ? 0 : this.getAccountMethod().hashCode());
		result = 37 * result + (getElectricType() == null ? 0 : this.getElectricType().hashCode());
		result = 37 * result + (getElectricAmount() == null ? 0 : this.getElectricAmount().hashCode());
		result = 37 * result + (getElectricPrice() == null ? 0 : this.getElectricPrice().hashCode());
		result = 37 * result + (getAccountAmount() == null ? 0 : this.getAccountAmount().hashCode());
		result = 37 * result + (getTax() == null ? 0 : this.getTax().hashCode());
		result = 37 * result + (getPayMethod() == null ? 0 : this.getPayMethod().hashCode());
		result = 37 * result + (getUtilitiesFee() == null ? 0 : this.getUtilitiesFee().hashCode());
		result = 37 * result + (getSewageFee() == null ? 0 : this.getSewageFee().hashCode());
		result = 37 * result + (getGarbageFee() == null ? 0 : this.getGarbageFee().hashCode());
		result = 37 * result + (getAccountCenterName() == null ? 0 : this.getAccountCenterName().hashCode());
		result = 37 * result + (getAccountCenterId() == null ? 0 : this.getAccountCenterId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getAdvancePayment() == null ? 0 : this.getAdvancePayment().hashCode());
		result = 37 * result + (getSettlementType() == null ? 0 : this.getSettlementType().hashCode());
		result = 37 * result + (getBillType() == null ? 0 : this.getBillType().hashCode());
		result = 37 * result + (getIs10kv() == null ? 0 : this.getIs10kv().hashCode());
		return result;
	}

}
