package bean;
// Generated 2018-1-3 15:04:16 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * Vw10kvdataId generated by hbm2java
 */
public class Vw10kvdataId implements java.io.Serializable {

	private String entityName;
	private BigDecimal totalElectricity;
	private String accountDate;
	private String userId;
	private String districtCompany;
	private BigDecimal totalAmount;

	public Vw10kvdataId() {
	}

	public Vw10kvdataId(String entityName, String accountDate, String districtCompany) {
		this.entityName = entityName;
		this.accountDate = accountDate;
		this.districtCompany = districtCompany;
	}

	public Vw10kvdataId(String entityName, BigDecimal totalElectricity, String accountDate, String userId,
			String districtCompany, BigDecimal totalAmount) {
		this.entityName = entityName;
		this.totalElectricity = totalElectricity;
		this.accountDate = accountDate;
		this.userId = userId;
		this.districtCompany = districtCompany;
		this.totalAmount = totalAmount;
	}

	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	public BigDecimal getTotalElectricity() {
		return this.totalElectricity;
	}

	public void setTotalElectricity(BigDecimal totalElectricity) {
		this.totalElectricity = totalElectricity;
	}

	public String getAccountDate() {
		return this.accountDate;
	}

	public void setAccountDate(String accountDate) {
		this.accountDate = accountDate;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getDistrictCompany() {
		return this.districtCompany;
	}

	public void setDistrictCompany(String districtCompany) {
		this.districtCompany = districtCompany;
	}

	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Vw10kvdataId))
			return false;
		Vw10kvdataId castOther = (Vw10kvdataId) other;

		return ((this.getEntityName() == castOther.getEntityName()) || (this.getEntityName() != null
				&& castOther.getEntityName() != null && this.getEntityName().equals(castOther.getEntityName())))
				&& ((this.getTotalElectricity() == castOther.getTotalElectricity())
						|| (this.getTotalElectricity() != null && castOther.getTotalElectricity() != null
								&& this.getTotalElectricity().equals(castOther.getTotalElectricity())))
				&& ((this.getAccountDate() == castOther.getAccountDate())
						|| (this.getAccountDate() != null && castOther.getAccountDate() != null
								&& this.getAccountDate().equals(castOther.getAccountDate())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getDistrictCompany() == castOther.getDistrictCompany())
						|| (this.getDistrictCompany() != null && castOther.getDistrictCompany() != null
								&& this.getDistrictCompany().equals(castOther.getDistrictCompany())))
				&& ((this.getTotalAmount() == castOther.getTotalAmount())
						|| (this.getTotalAmount() != null && castOther.getTotalAmount() != null
								&& this.getTotalAmount().equals(castOther.getTotalAmount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEntityName() == null ? 0 : this.getEntityName().hashCode());
		result = 37 * result + (getTotalElectricity() == null ? 0 : this.getTotalElectricity().hashCode());
		result = 37 * result + (getAccountDate() == null ? 0 : this.getAccountDate().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getDistrictCompany() == null ? 0 : this.getDistrictCompany().hashCode());
		result = 37 * result + (getTotalAmount() == null ? 0 : this.getTotalAmount().hashCode());
		return result;
	}

}
