package bean;
// Generated 2018-1-3 15:04:16 by Hibernate Tools 3.5.0.Final

/**
 * Vw10kvdata generated by hbm2java
 */
public class Vw10kvdata implements java.io.Serializable {

	private Vw10kvdataId id;

	public Vw10kvdata() {
	}

	public Vw10kvdata(Vw10kvdataId id) {
		this.id = id;
	}

	public Vw10kvdataId getId() {
		return this.id;
	}

	public void setId(Vw10kvdataId id) {
		this.id = id;
	}

}
