package bean;
// Generated 2017-12-22 15:37:05 by Hibernate Tools 3.5.0.Final

/**
 * VwAllConditions generated by hbm2java
 */
public class VwAllConditions implements java.io.Serializable {

	private VwAllConditionsId id;

	public VwAllConditions() {
	}

	public VwAllConditions(VwAllConditionsId id) {
		this.id = id;
	}

	public VwAllConditionsId getId() {
		return this.id;
	}

	public void setId(VwAllConditionsId id) {
		this.id = id;
	}

}
