package bean;
// Generated 2017-12-22 15:37:05 by Hibernate Tools 3.5.0.Final

/**
 * VwAllConditionsYear generated by hbm2java
 */
public class VwAllConditionsYear implements java.io.Serializable {

	private VwAllConditionsYearId id;

	public VwAllConditionsYear() {
	}

	public VwAllConditionsYear(VwAllConditionsYearId id) {
		this.id = id;
	}

	public VwAllConditionsYearId getId() {
		return this.id;
	}

	public void setId(VwAllConditionsYearId id) {
		this.id = id;
	}

}
